// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AkarIconsCalendar: typeof import('~icons/akar-icons/calendar')['default']
    ArticleMeta: typeof import('./components/blog/ArticleMeta.vue')['default']
    ArticlesList: typeof import('./components/blog/ArticlesList.vue')['default']
    BaseAlert: typeof import('./components/BaseAlert.vue')['default']
    BlockQuote: typeof import('./components/blog/posts/BlockQuote.vue')['default']
    CarbonCode: typeof import('~icons/carbon/code')['default']
    CarbonCurrencyDollar: typeof import('~icons/carbon/currency-dollar')['default']
    CarbonEmail: typeof import('~icons/carbon/email')['default']
    CarbonHourglass: typeof import('~icons/carbon/hourglass')['default']
    CarbonLicenseMaintenance: typeof import('~icons/carbon/license-maintenance')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonLogoLinkedin: typeof import('~icons/carbon/logo-linkedin')['default']
    CarbonLogoTwitter: typeof import('~icons/carbon/logo-twitter')['default']
    CarbonLogoYoutube: typeof import('~icons/carbon/logo-youtube')['default']
    CarbonOpacity: typeof import('~icons/carbon/opacity')['default']
    CarbonRepeat: typeof import('~icons/carbon/repeat')['default']
    Copyright: typeof import('./components/footer/Copyright.vue')['default']
    FluentTopSpeed20Filled: typeof import('~icons/fluent/top-speed20-filled')['default']
    FooterIcon: typeof import('./components/footer/FooterIcon.vue')['default']
    GravatarImage: typeof import('./components/author/GravatarImage.vue')['default']
    Icon: typeof import('~icons/ic/on')['default']
    IcSharpWineBar: typeof import('~icons/ic/sharp-wine-bar')['default']
    LaBroom: typeof import('~icons/la/broom')['default']
    LayoutTwoColumns: typeof import('./components/blog/posts/LayoutTwoColumns.vue')['default']
    PhBrain: typeof import('~icons/ph/brain')['default']
    PhSkull: typeof import('~icons/ph/skull')['default']
    PhWallFill: typeof import('~icons/ph/wall-fill')['default']
    ProConList: typeof import('./components/ProConList.vue')['default']
    README: typeof import('./components/README.md')['default']
    SiteFooter: typeof import('./components/footer/SiteFooter.vue')['default']
    SiteHeader: typeof import('./components/header/SiteHeader.vue')['default']
    TablerCrane: typeof import('~icons/tabler/crane')['default']
  }
}

export { }
