// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "vue" {
  export interface GlobalComponents {
    ArticleMeta: typeof import("./components/blog/ArticleMeta.vue")["default"]
    ArticlesList: typeof import("./components/blog/ArticlesList.vue")["default"]
    BaseAlert: typeof import("./components/BaseAlert.vue")["default"]
    BlockQuote: typeof import("./components/blog/posts/BlockQuote.vue")["default"]
    CarbonEmail: typeof import("~icons/carbon/email")["default"]
    CarbonInformationFilled: typeof import("~icons/carbon/information-filled")["default"]
    CarbonLogoGithub: typeof import("~icons/carbon/logo-github")["default"]
    CarbonLogoLinkedin: typeof import("~icons/carbon/logo-linkedin")["default"]
    CarbonLogoTwitter: typeof import("~icons/carbon/logo-twitter")["default"]
    CarbonLogoYoutube: typeof import("~icons/carbon/logo-youtube")["default"]
    CarbonNextOutline: typeof import("~icons/carbon/next-outline")["default"]
    CarbonNotebook: typeof import("~icons/carbon/notebook")["default"]
    CarbonStarFilled: typeof import("~icons/carbon/star-filled")["default"]
    Copyright: typeof import("./components/footer/Copyright.vue")["default"]
    FooterIcon: typeof import("./components/footer/FooterIcon.vue")["default"]
    GravatarImage: typeof import("./components/author/GravatarImage.vue")["default"]
    LayoutTwoColumns: typeof import("./components/blog/posts/LayoutTwoColumns.vue")["default"]
    ProConList: typeof import("./components/ProConList.vue")["default"]
    README: typeof import("./components/README.md")["default"]
    SiteFooter: typeof import("./components/footer/SiteFooter.vue")["default"]
    SiteHeader: typeof import("./components/header/SiteHeader.vue")["default"]
  }
}

export {}
